language: node_js
node_js:
  - 11
addons:
  packages:
    - libgconf-2-4
cache:
  directories:
    - ~/.cache
script:
  - eslint 'src/**'
  - npm run test:coveralls
notifications:
  email: false
  before_script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s
    - export PATH=$HOME/.yarn/bin:$PATH
    - yarn install
